config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :popos

  root 'welcome#index'

end

app/models/popo.rb
class Popo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/popos_controller.rb
class PoposController < ApplicationController
  before_action :set_popo, only: [:show, :edit, :update, :destroy]

  # GET /popos
  # GET /popos.json
  def index
    @popos = Popo.all
  end

  # GET /popos/1
  # GET /popos/1.json
  def show
  end

  # GET /popos/new
  def new
    @popo = Popo.new
  end

  # GET /popos/1/edit
  def edit
  end

  # POST /popos
  # POST /popos.json
  def create
    @popo = Popo.new(popo_params)

    respond_to do |format|
      if @popo.save
        format.html { redirect_to @popo, notice: 'Popo was successfully created.' }
        format.json { render :show, status: :created, location: @popo }
      else
        format.html { render :new }
        format.json { render json: @popo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /popos/1
  # PATCH/PUT /popos/1.json
  def update
    respond_to do |format|
      if @popo.update(popo_params)
        format.html { redirect_to @popo, notice: 'Popo was successfully updated.' }
        format.json { render :show, status: :ok, location: @popo }
      else
        format.html { render :edit }
        format.json { render json: @popo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /popos/1
  # DELETE /popos/1.json
  def destroy
    @popo.destroy
    respond_to do |format|
      format.html { redirect_to popos_url, notice: 'Popo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_popo
      @popo = Popo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def popo_params
      params.require(:popo).permit(:title)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/popos_helper.rb
module PoposHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/popos/_form.html.erb
<%= form_for(@popo) do |f| %>
  <% if @popo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@popo.errors.count, "error") %> prohibited this popo from being saved:</h2>

      <ul>
      <% @popo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/popos/edit.html.erb
<h1>Editing Popo</h1>

<%= render 'form' %>

<%= link_to 'Show', @popo %> |
<%= link_to 'Back', popos_path %>

app/views/popos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Popos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @popos.each do |popo| %>
      <tr>
        <td><%= popo.title %></td>
        <td><%= link_to 'Show', popo %></td>
        <td><%= link_to 'Edit', edit_popo_path(popo) %></td>
        <td><%= link_to 'Destroy', popo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Popo', new_popo_path %>

app/views/popos/new.html.erb
<h1>New Popo</h1>

<%= render 'form' %>

<%= link_to 'Back', popos_path %>

app/views/popos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @popo.title %>
</p>

<%= link_to 'Edit', edit_popo_path(@popo) %> |
<%= link_to 'Back', popos_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>